### DISCUSSION TITLE
Externalise schema locations

### DISCUSSION THREAD

**Discussion by onomesotu** [Netflix/dgs-framework#1108] [Q&A]
It seems like it's not possible to externalize the GQL schema location. 
Given the below application.yml configuration:
```
dgs:
  graphql:
    schema-locations:
      - ${GRAPHQL_SCHEMA_LOCATION:classpath*:graphql-schemas/**/*.graphql*}
```
Where `GRAPHQL_SCHEMA_LOCATION` is a location in the system outside the app. 
Springboot fails to start with the following error:

```
Caused by: com.netflix.graphql.dgs.exceptions.NoSchemaFoundException: No schema files found. Define schemas in src/main/resources/schema/*.graphqls
```

Does this mean the schema locations cannot be set to any arbitrary external system location?
