### ISSUE TITLE
Spring webflux: Consider defining a bean of type 'graphql.schema.GraphQLSchema' in your configuration.

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [Netflix/dgs-framework#1069]
Version:
springboot:2.7.0 
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.netflix.graphql.dgs</groupId>
                <artifactId>graphql-dgs-platform-dependencies</artifactId>
                <version>4.9.16</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependency>
        <groupId>com.netflix.graphql.dgs</groupId>
        <artifactId>graphql-dgs-webflux-starter</artifactId>
    </dependency>
```

The yml config
```
spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude: com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration
dgs:
  graphql:
    schema-locations: classpath*:graphql/**/*.graphql*
    path: /graphql
```
Has error below:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method dgsReactiveQueryExecutor in com.netflix.graphql.dgs.webflux.autoconfiguration.DgsWebFluxAutoConfiguration required a bean of type 'graphql.schema.GraphQLSchema' that could not be found.


Action:

Consider defining a bean of type 'graphql.schema.GraphQLSchema' in your configuration.
```
