### ISSUE TITLE
bug: DGS metrics stop reporting Spring Boot 2.6.10, micrometer-core 1.88

### ISSUE THREAD

**Issue by deweyjose** [Netflix/dgs-framework#1249]
Hi team,

We have projects that have upgrade to Spring Boot 2.6.10 and have seemingly lost all of the DGS loader, fetcher and query metrics.

It looks like we're at micrometer-core 1.8.8 now. Should this version of spring-boot/micrometer be compatible with `graphql-dgs-spring-boot-micrometer` ?

Thanks in advance, let me know if you need any more information.

**Comment by deweyjose** [comment]
Hi there, it looks like the issue was related to how metrics were pushed. They moved from Histograms to Distributions. Closing this :)

**Comment by deweyjose** [comment]
Actually - going to reopen this.  We have the following configured in our application.yaml configuration:

```
    dgs-graphql:
      autotime:
        percentiles: [ 0.50,0.75,0.90,0.95,0.99 ]
        percentiles-histogram: true
```

micrometer is pushing Distributions instead.
